image: amazonlinux:latest

pipelines:
  default:
    - step:
        script:
          - yum update -y
          - yum install -y zip
          - zip -r application1.zip .
          - aws deploy push --application-name $APPLICATION_NAME --s3-location s3://$S3_BUCKET/application1.zip --source application1.zip --region $AWS_DEFAULT_REGION
          - aws deploy create-deployment --application-name $APPLICATION_NAME --deployment-group-name $DEPLOYMENT_GROUP --s3-location bucket=$S3_BUCKET,key=application1.zip,bundleType=zip --region $AWS_DEFAULT_REGION --deployment-config-name CodeDeployDefault.OneAtATime --description "Deploying my-app-1.0.0" --file-exists-behavior OVERWRITE --ignore-application-stop-failures
